# Generated by Django 4.2.7 on 2023-12-22 19:08

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(
                validators=[student.models.models.validate_age]),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=5)),
                ('student', models.ManyToManyField(to='student.student')),
            ],
        ),
    ]
